"""RobotWin benchmark — data config, embodiment tags, and mixtures."""

from starVLA.dataloader.gr00t_lerobot.datasets import ModalityConfig
from starVLA.dataloader.gr00t_lerobot.transform.base import ComposedModalityTransform
from starVLA.dataloader.gr00t_lerobot.transform.state_action import StateActionToTensor, StateActionTransform
from starVLA.dataloader.gr00t_lerobot.embodiment_tags import EmbodimentTag


# ---------------------------------------------------------------------------
# DataConfig — Agilex (RobotWin, action_indices=16)
# ---------------------------------------------------------------------------
class AgilexDataConfig:
    embodiment_tag = EmbodimentTag.NEW_EMBODIMENT
    video_keys = ["video.cam_high", "video.cam_left_wrist", "video.cam_right_wrist"]
    state_keys = ["state.left_joints", "state.right_joints", "state.left_gripper", "state.right_gripper"]
    action_keys = ["action.left_joints", "action.right_joints", "action.left_gripper", "action.right_gripper"]
    # Per-key dims for PolicyNormProcessor (Agilex 6-DOF arms + binary gripper = 14-D total)
    action_key_dims = {"action.left_joints": 6, "action.right_joints": 6, "action.left_gripper": 1, "action.right_gripper": 1}
    state_key_dims  = {"state.left_joints": 6, "state.right_joints": 6, "state.left_gripper": 1, "state.right_gripper": 1}
    language_keys = ["annotation.human.action.task_description"]
    observation_indices = list(range(51)) #[0]
    action_indices = list(range(16))

    def modality_config(self):
        return {
            "video": ModalityConfig(delta_indices=self.observation_indices, modality_keys=self.video_keys),
            "state": ModalityConfig(delta_indices=self.observation_indices, modality_keys=self.state_keys),
            "action": ModalityConfig(delta_indices=self.action_indices, modality_keys=self.action_keys),
            "language": ModalityConfig(delta_indices=self.observation_indices, modality_keys=self.language_keys),
        }

    def transform(self):
        return ComposedModalityTransform(transforms=[
            StateActionToTensor(apply_to=self.state_keys),
            StateActionTransform(
                apply_to=self.state_keys,
                normalization_modes={
                    "state.left_joints": "min_max", "state.right_joints": "min_max",
                    "state.left_gripper": "binary", "state.right_gripper": "binary",
                },
            ),
            StateActionToTensor(apply_to=self.action_keys),
            StateActionTransform(
                apply_to=self.action_keys,
                normalization_modes={
                    "action.left_joints": "min_max", "action.right_joints": "min_max",
                    "action.left_gripper": "binary", "action.right_gripper": "binary",
                },
            ),
        ])


# ---------------------------------------------------------------------------
# DataConfig — Agilex 50 (action_indices=50)
# ---------------------------------------------------------------------------
class AgilexData50Config(AgilexDataConfig):
    action_indices = list(range(50))

    def transform(self):
        return ComposedModalityTransform(transforms=[
            StateActionToTensor(apply_to=self.state_keys),
            StateActionTransform(
                apply_to=self.state_keys,
                binary_threshold=0.49,
                normalization_modes={
                    "state.left_joints": "min_max", "state.right_joints": "min_max",
                    "state.left_gripper": "binary", "state.right_gripper": "binary",
                },
            ),
            StateActionToTensor(apply_to=self.action_keys),
            StateActionTransform(
                apply_to=self.action_keys,
                binary_threshold=0.49,
                normalization_modes={
                    "action.left_joints": "min_max", "action.right_joints": "min_max",
                    "action.left_gripper": "binary", "action.right_gripper": "binary",
                },
            ),
        ])


# ---------------------------------------------------------------------------
# DataConfig — ARX X5
# ---------------------------------------------------------------------------
class ArxX5DataConfig:
    embodiment_tag = EmbodimentTag.NEW_EMBODIMENT
    video_keys = ["video.cam_high", "video.cam_left_wrist", "video.cam_right_wrist"]
    state_keys = ["state.left_joints", "state.right_joints", "state.left_gripper", "state.right_gripper"]
    action_keys = ["action.left_joints", "action.right_joints", "action.left_gripper", "action.right_gripper"]
    language_keys = ["annotation.human.action.task_description"]
    observation_indices = [0]
    action_indices = list(range(16))

    def modality_config(self):
        return {
            "video": ModalityConfig(delta_indices=self.observation_indices, modality_keys=self.video_keys),
            "state": ModalityConfig(delta_indices=self.observation_indices, modality_keys=self.state_keys),
            "action": ModalityConfig(delta_indices=self.action_indices, modality_keys=self.action_keys),
            "language": ModalityConfig(delta_indices=self.observation_indices, modality_keys=self.language_keys),
        }

    def transform(self):
        return ComposedModalityTransform(transforms=[
            StateActionToTensor(apply_to=self.state_keys),
            StateActionTransform(
                apply_to=self.state_keys,
                normalization_modes={
                    "state.left_joints": "min_max", "state.right_joints": "min_max",
                    "state.left_gripper": "binary", "state.right_gripper": "binary",
                },
            ),
            StateActionToTensor(apply_to=self.action_keys),
            StateActionTransform(
                apply_to=self.action_keys,
                normalization_modes={
                    "action.left_joints": "min_max", "action.right_joints": "min_max",
                    "action.left_gripper": "binary", "action.right_gripper": "binary",
                },
            ),
        ])


ROBOT_TYPE_CONFIG_MAP = {
    "robotwin": AgilexDataConfig(),
    "robotwin50": AgilexData50Config(),
    "arx_x5": ArxX5DataConfig(),
}

ROBOT_TYPE_TO_EMBODIMENT_TAG = {
    # Per Proposal A, embodiment_tag now lives as a classvar on each DataConfig.
    # The registry derives ROBOT_TYPE_TO_EMBODIMENT_TAG automatically. Kept as
    # an empty dict for backward compat (it is honored as legacy override).
}

# ---------------------------------------------------------------------------
# Mixtures
# ---------------------------------------------------------------------------
DATASET_NAMED_MIXTURES = {
    "robotwin_all": [
        ("Clean/adjust_bottle", 1.0, "robotwin"), ("Randomized/adjust_bottle", 1.0, "robotwin"),
        ("Clean/beat_block_hammer", 1.0, "robotwin"), ("Randomized/beat_block_hammer", 1.0, "robotwin"),
        ("Clean/blocks_ranking_rgb", 1.0, "robotwin"), ("Randomized/blocks_ranking_rgb", 1.0, "robotwin"),
        ("Clean/blocks_ranking_size", 1.0, "robotwin"), ("Randomized/blocks_ranking_size", 1.0, "robotwin"),
        ("Clean/click_alarmclock", 1.0, "robotwin"), ("Randomized/click_alarmclock", 1.0, "robotwin"),
        ("Clean/click_bell", 1.0, "robotwin"), ("Randomized/click_bell", 1.0, "robotwin"),
        ("Clean/dump_bin_bigbin", 1.0, "robotwin"), ("Randomized/dump_bin_bigbin", 1.0, "robotwin"),
        ("Clean/grab_roller", 1.0, "robotwin"), ("Randomized/grab_roller", 1.0, "robotwin"),
        ("Clean/handover_block", 1.0, "robotwin"), ("Randomized/handover_block", 1.0, "robotwin"),
        ("Clean/handover_mic", 1.0, "robotwin"), ("Randomized/handover_mic", 1.0, "robotwin"),
        ("Clean/hanging_mug", 1.0, "robotwin"), ("Randomized/hanging_mug", 1.0, "robotwin"),
        ("Clean/lift_pot", 1.0, "robotwin"), ("Randomized/lift_pot", 1.0, "robotwin"),
        ("Clean/move_can_pot", 1.0, "robotwin"), ("Randomized/move_can_pot", 1.0, "robotwin"),
        ("Clean/move_pillbottle_pad", 1.0, "robotwin"), ("Randomized/move_pillbottle_pad", 1.0, "robotwin"),
        ("Clean/move_playingcard_away", 1.0, "robotwin"), ("Randomized/move_playingcard_away", 1.0, "robotwin"),
        ("Clean/move_stapler_pad", 1.0, "robotwin"), ("Randomized/move_stapler_pad", 1.0, "robotwin"),
        ("Clean/open_laptop", 1.0, "robotwin"), ("Randomized/open_laptop", 1.0, "robotwin"),
        ("Clean/open_microwave", 1.0, "robotwin"), ("Randomized/open_microwave", 1.0, "robotwin"),
        ("Clean/pick_diverse_bottles", 1.0, "robotwin"), ("Randomized/pick_diverse_bottles", 1.0, "robotwin"),
        ("Clean/pick_dual_bottles", 1.0, "robotwin"), ("Randomized/pick_dual_bottles", 1.0, "robotwin"),
        ("Clean/place_a2b_left", 1.0, "robotwin"), ("Randomized/place_a2b_left", 1.0, "robotwin"),
        ("Clean/place_a2b_right", 1.0, "robotwin"), ("Randomized/place_a2b_right", 1.0, "robotwin"),
        ("Clean/place_bread_basket", 1.0, "robotwin"), ("Randomized/place_bread_basket", 1.0, "robotwin"),
        ("Clean/place_bread_skillet", 1.0, "robotwin"), ("Randomized/place_bread_skillet", 1.0, "robotwin"),
        ("Clean/place_burger_fries", 1.0, "robotwin"), ("Randomized/place_burger_fries", 1.0, "robotwin"),
        ("Clean/place_can_basket", 1.0, "robotwin"), ("Randomized/place_can_basket", 1.0, "robotwin"),
        ("Clean/place_cans_plasticbox", 1.0, "robotwin"), ("Randomized/place_cans_plasticbox", 1.0, "robotwin"),
        ("Clean/place_container_plate", 1.0, "robotwin"), ("Randomized/place_container_plate", 1.0, "robotwin"),
        ("Clean/place_dual_shoes", 1.0, "robotwin"), ("Randomized/place_dual_shoes", 1.0, "robotwin"),
        ("Clean/place_empty_cup", 1.0, "robotwin"), ("Randomized/place_empty_cup", 1.0, "robotwin"),
        ("Clean/place_fan", 1.0, "robotwin"), ("Randomized/place_fan", 1.0, "robotwin"),
        ("Clean/place_mouse_pad", 1.0, "robotwin"), ("Randomized/place_mouse_pad", 1.0, "robotwin"),
        ("Clean/place_object_basket", 1.0, "robotwin"), ("Randomized/place_object_basket", 1.0, "robotwin"),
        ("Clean/place_object_scale", 1.0, "robotwin"), ("Randomized/place_object_scale", 1.0, "robotwin"),
        ("Clean/place_object_stand", 1.0, "robotwin"), ("Randomized/place_object_stand", 1.0, "robotwin"),
        ("Clean/place_phone_stand", 1.0, "robotwin"), ("Randomized/place_phone_stand", 1.0, "robotwin"),
        ("Clean/place_shoe", 1.0, "robotwin"), ("Randomized/place_shoe", 1.0, "robotwin"),
        ("Clean/press_stapler", 1.0, "robotwin"), ("Randomized/press_stapler", 1.0, "robotwin"),
        ("Clean/put_bottles_dustbin", 1.0, "robotwin"), ("Randomized/put_bottles_dustbin", 1.0, "robotwin"),
        ("Clean/put_object_cabinet", 1.0, "robotwin"), ("Randomized/put_object_cabinet", 1.0, "robotwin"),
        ("Clean/rotate_qrcode", 1.0, "robotwin"), ("Randomized/rotate_qrcode", 1.0, "robotwin"),
        ("Clean/scan_object", 1.0, "robotwin"), ("Randomized/scan_object", 1.0, "robotwin"),
        ("Clean/shake_bottle", 1.0, "robotwin"), ("Randomized/shake_bottle", 1.0, "robotwin"),
        ("Clean/shake_bottle_horizontally", 1.0, "robotwin"), ("Randomized/shake_bottle_horizontally", 1.0, "robotwin"),
        ("Clean/stack_blocks_three", 1.0, "robotwin"), ("Randomized/stack_blocks_three", 1.0, "robotwin"),
        ("Clean/stack_blocks_two", 1.0, "robotwin"), ("Randomized/stack_blocks_two", 1.0, "robotwin"),
        ("Clean/stack_bowls_three", 1.0, "robotwin"), ("Randomized/stack_bowls_three", 1.0, "robotwin"),
        ("Clean/stack_bowls_two", 1.0, "robotwin"), ("Randomized/stack_bowls_two", 1.0, "robotwin"),
        ("Clean/stamp_seal", 1.0, "robotwin"), ("Randomized/stamp_seal", 1.0, "robotwin"),
        ("Clean/turn_switch", 1.0, "robotwin"), ("Randomized/turn_switch", 1.0, "robotwin"),
    ],
    "robotwin_all_50": [
        ("Clean/adjust_bottle", 1.0, "robotwin50"), ("Randomized/adjust_bottle", 1.0, "robotwin50"),
        ("Clean/beat_block_hammer", 1.0, "robotwin50"), ("Randomized/beat_block_hammer", 1.0, "robotwin50"),
        ("Clean/blocks_ranking_rgb", 1.0, "robotwin50"), ("Randomized/blocks_ranking_rgb", 1.0, "robotwin50"),
        ("Clean/blocks_ranking_size", 1.0, "robotwin50"), ("Randomized/blocks_ranking_size", 1.0, "robotwin50"),
        ("Clean/click_alarmclock", 1.0, "robotwin50"), ("Randomized/click_alarmclock", 1.0, "robotwin50"),
        ("Clean/click_bell", 1.0, "robotwin50"), ("Randomized/click_bell", 1.0, "robotwin50"),
        ("Clean/dump_bin_bigbin", 1.0, "robotwin50"), ("Randomized/dump_bin_bigbin", 1.0, "robotwin50"),
        ("Clean/grab_roller", 1.0, "robotwin50"), ("Randomized/grab_roller", 1.0, "robotwin50"),
        ("Clean/handover_block", 1.0, "robotwin50"), ("Randomized/handover_block", 1.0, "robotwin50"),
        ("Clean/handover_mic", 1.0, "robotwin50"), ("Randomized/handover_mic", 1.0, "robotwin50"),
        ("Clean/hanging_mug", 1.0, "robotwin50"), ("Randomized/hanging_mug", 1.0, "robotwin50"),
        ("Clean/lift_pot", 1.0, "robotwin50"), ("Randomized/lift_pot", 1.0, "robotwin50"),
        ("Clean/move_can_pot", 1.0, "robotwin50"), ("Randomized/move_can_pot", 1.0, "robotwin50"),
        ("Clean/move_pillbottle_pad", 1.0, "robotwin50"), ("Randomized/move_pillbottle_pad", 1.0, "robotwin50"),
        ("Clean/move_playingcard_away", 1.0, "robotwin50"), ("Randomized/move_playingcard_away", 1.0, "robotwin50"),
        ("Clean/move_stapler_pad", 1.0, "robotwin50"), ("Randomized/move_stapler_pad", 1.0, "robotwin50"),
        ("Clean/open_laptop", 1.0, "robotwin50"), ("Randomized/open_laptop", 1.0, "robotwin50"),
        ("Clean/open_microwave", 1.0, "robotwin50"), ("Randomized/open_microwave", 1.0, "robotwin50"),
        ("Clean/pick_diverse_bottles", 1.0, "robotwin50"), ("Randomized/pick_diverse_bottles", 1.0, "robotwin50"),
        ("Clean/pick_dual_bottles", 1.0, "robotwin50"), ("Randomized/pick_dual_bottles", 1.0, "robotwin50"),
        ("Clean/place_a2b_left", 1.0, "robotwin50"), ("Randomized/place_a2b_left", 1.0, "robotwin50"),
        ("Clean/place_a2b_right", 1.0, "robotwin50"), ("Randomized/place_a2b_right", 1.0, "robotwin50"),
        ("Clean/place_bread_basket", 1.0, "robotwin50"), ("Randomized/place_bread_basket", 1.0, "robotwin50"),
        ("Clean/place_bread_skillet", 1.0, "robotwin50"), ("Randomized/place_bread_skillet", 1.0, "robotwin50"),
        ("Clean/place_burger_fries", 1.0, "robotwin50"), ("Randomized/place_burger_fries", 1.0, "robotwin50"),
        ("Clean/place_can_basket", 1.0, "robotwin50"), ("Randomized/place_can_basket", 1.0, "robotwin50"),
        ("Clean/place_cans_plasticbox", 1.0, "robotwin50"), ("Randomized/place_cans_plasticbox", 1.0, "robotwin50"),
        ("Clean/place_container_plate", 1.0, "robotwin50"), ("Randomized/place_container_plate", 1.0, "robotwin50"),
        ("Clean/place_dual_shoes", 1.0, "robotwin50"), ("Randomized/place_dual_shoes", 1.0, "robotwin50"),
        ("Clean/place_empty_cup", 1.0, "robotwin50"), ("Randomized/place_empty_cup", 1.0, "robotwin50"),
        ("Clean/place_fan", 1.0, "robotwin50"), ("Randomized/place_fan", 1.0, "robotwin50"),
        ("Clean/place_mouse_pad", 1.0, "robotwin50"), ("Randomized/place_mouse_pad", 1.0, "robotwin50"),
        ("Clean/place_object_basket", 1.0, "robotwin50"), ("Randomized/place_object_basket", 1.0, "robotwin50"),
        ("Clean/place_object_scale", 1.0, "robotwin50"), ("Randomized/place_object_scale", 1.0, "robotwin50"),
        ("Clean/place_object_stand", 1.0, "robotwin50"), ("Randomized/place_object_stand", 1.0, "robotwin50"),
        ("Clean/place_phone_stand", 1.0, "robotwin50"), ("Randomized/place_phone_stand", 1.0, "robotwin50"),
        ("Clean/place_shoe", 1.0, "robotwin50"), ("Randomized/place_shoe", 1.0, "robotwin50"),
        ("Clean/press_stapler", 1.0, "robotwin50"), ("Randomized/press_stapler", 1.0, "robotwin50"),
        ("Clean/put_bottles_dustbin", 1.0, "robotwin50"), ("Randomized/put_bottles_dustbin", 1.0, "robotwin50"),
        ("Clean/put_object_cabinet", 1.0, "robotwin50"), ("Randomized/put_object_cabinet", 1.0, "robotwin50"),
        ("Clean/rotate_qrcode", 1.0, "robotwin50"), ("Randomized/rotate_qrcode", 1.0, "robotwin50"),
        ("Clean/scan_object", 1.0, "robotwin50"), ("Randomized/scan_object", 1.0, "robotwin50"),
        ("Clean/shake_bottle", 1.0, "robotwin50"), ("Randomized/shake_bottle", 1.0, "robotwin50"),
        ("Clean/shake_bottle_horizontally", 1.0, "robotwin50"), ("Randomized/shake_bottle_horizontally", 1.0, "robotwin50"),
        ("Clean/stack_blocks_three", 1.0, "robotwin50"), ("Randomized/stack_blocks_three", 1.0, "robotwin50"),
        ("Clean/stack_blocks_two", 1.0, "robotwin50"), ("Randomized/stack_blocks_two", 1.0, "robotwin50"),
        ("Clean/stack_bowls_three", 1.0, "robotwin50"), ("Randomized/stack_bowls_three", 1.0, "robotwin50"),
        ("Clean/stack_bowls_two", 1.0, "robotwin50"), ("Randomized/stack_bowls_two", 1.0, "robotwin50"),
        ("Clean/stamp_seal", 1.0, "robotwin50"), ("Randomized/stamp_seal", 1.0, "robotwin50"),
        ("Clean/turn_switch", 1.0, "robotwin50"), ("Randomized/turn_switch", 1.0, "robotwin50"),
    ],
    "robotwin": [
        ("adjust_bottle", 1.0, "robotwin"),
        ("beat_block_hammer", 1.0, "robotwin"),
        ("blocks_ranking_rgb", 1.0, "robotwin"),
        ("blocks_ranking_size", 1.0, "robotwin"),
        ("click_alarmclock", 1.0, "robotwin"),
        ("click_bell", 1.0, "robotwin"),
        ("dump_bin_bigbin", 1.0, "robotwin"),
        ("grab_roller", 1.0, "robotwin"),
        ("handover_block", 1.0, "robotwin"),
        ("handover_mic", 1.0, "robotwin"),
        ("hanging_mug", 1.0, "robotwin"),
        ("lift_pot", 1.0, "robotwin"),
        ("move_can_pot", 1.0, "robotwin"),
        ("move_pillbottle_pad", 1.0, "robotwin"),
        ("move_playingcard_away", 1.0, "robotwin"),
        ("move_stapler_pad", 1.0, "robotwin"),
        ("open_laptop", 1.0, "robotwin"),
        ("open_microwave", 1.0, "robotwin"),
        ("pick_diverse_bottles", 1.0, "robotwin"),
        ("pick_dual_bottles", 1.0, "robotwin"),
        ("place_a2b_left", 1.0, "robotwin"),
        ("place_a2b_right", 1.0, "robotwin"),
        ("place_bread_basket", 1.0, "robotwin"),
        ("place_bread_skillet", 1.0, "robotwin"),
        ("place_burger_fries", 1.0, "robotwin"),
        ("place_can_basket", 1.0, "robotwin"),
        ("place_cans_plasticbox", 1.0, "robotwin"),
        ("place_container_plate", 1.0, "robotwin"),
        ("place_dual_shoes", 1.0, "robotwin"),
        ("place_empty_cup", 1.0, "robotwin"),
        ("place_fan", 1.0, "robotwin"),
        ("place_mouse_pad", 1.0, "robotwin"),
        ("place_object_basket", 1.0, "robotwin"),
        ("place_object_scale", 1.0, "robotwin"),
        ("place_object_stand", 1.0, "robotwin"),
        ("place_phone_stand", 1.0, "robotwin"),
        ("place_shoe", 1.0, "robotwin"),
        ("press_stapler", 1.0, "robotwin"),
        ("put_bottles_dustbin", 1.0, "robotwin"),
        ("put_object_cabinet", 1.0, "robotwin"),
        ("rotate_qrcode", 1.0, "robotwin"),
        ("scan_object", 1.0, "robotwin"),
        ("shake_bottle", 1.0, "robotwin"),
        ("shake_bottle_horizontally", 1.0, "robotwin"),
        ("stack_blocks_three", 1.0, "robotwin"),
        ("stack_blocks_two", 1.0, "robotwin"),
        ("stack_bowls_three", 1.0, "robotwin"),
        ("stack_bowls_two", 1.0, "robotwin"),
        ("stamp_seal", 1.0, "robotwin"),
        ("turn_switch", 1.0, "robotwin"),
    ],
    "robotwin_task1": [("adjust_bottle", 1.0, "robotwin")],
    "robotwin_task2": [("place_a2b_left", 1.0, "robotwin"), ("place_a2b_right", 1.0, "robotwin")],
    "arx_x5": [("arx_x5", 1.0, "arx_x5")],
    "robotwin_lerobot_mix_50": [
        ("clean/adjust_bottle", 1.0, "robotwin50"),
        ("clean/beat_block_hammer", 1.0, "robotwin50"),
        ("clean/blocks_ranking_rgb", 1.0, "robotwin50"),
        ("clean/blocks_ranking_size", 1.0, "robotwin50"),
        ("clean/click_alarmclock", 1.0, "robotwin50"),
        ("clean/click_bell", 1.0, "robotwin50"),
        ("clean/dump_bin_bigbin", 1.0, "robotwin50"),
        ("clean/grab_roller", 1.0, "robotwin50"),
        ("clean/handover_block", 1.0, "robotwin50"),
        ("clean/handover_mic", 1.0, "robotwin50"),
        ("clean/hanging_mug", 1.0, "robotwin50"),
        ("clean/lift_pot", 1.0, "robotwin50"),
        ("clean/move_can_pot", 1.0, "robotwin50"),
        ("clean/move_pillbottle_pad", 1.0, "robotwin50"),
        ("clean/move_playingcard_away", 1.0, "robotwin50"),
        ("clean/move_stapler_pad", 1.0, "robotwin50"),
        ("clean/open_laptop", 1.0, "robotwin50"),
        ("clean/open_microwave", 1.0, "robotwin50"),
        ("clean/pick_diverse_bottles", 1.0, "robotwin50"),
        ("clean/pick_dual_bottles", 1.0, "robotwin50"),
        ("clean/place_a2b_left", 1.0, "robotwin50"),
        ("clean/place_a2b_right", 1.0, "robotwin50"),
        ("clean/place_bread_basket", 1.0, "robotwin50"),
        ("clean/place_bread_skillet", 1.0, "robotwin50"),
        ("clean/place_burger_fries", 1.0, "robotwin50"),
        ("clean/place_can_basket", 1.0, "robotwin50"),
        ("clean/place_cans_plasticbox", 1.0, "robotwin50"),
        ("clean/place_container_plate", 1.0, "robotwin50"),
        ("clean/place_dual_shoes", 1.0, "robotwin50"),
        ("clean/place_empty_cup", 1.0, "robotwin50"),
        ("clean/place_fan", 1.0, "robotwin50"),
        ("clean/place_mouse_pad", 1.0, "robotwin50"),
        ("clean/place_object_basket", 1.0, "robotwin50"),
        ("clean/place_object_scale", 1.0, "robotwin50"),
        ("clean/place_object_stand", 1.0, "robotwin50"),
        ("clean/place_phone_stand", 1.0, "robotwin50"),
        ("clean/place_shoe", 1.0, "robotwin50"),
        ("clean/press_stapler", 1.0, "robotwin50"),
        ("clean/put_bottles_dustbin", 1.0, "robotwin50"),
        ("clean/put_object_cabinet", 1.0, "robotwin50"),
        ("clean/rotate_qrcode", 1.0, "robotwin50"),
        ("clean/scan_object", 1.0, "robotwin50"),
        ("clean/shake_bottle", 1.0, "robotwin50"),
        ("clean/shake_bottle_horizontally", 1.0, "robotwin50"),
        ("clean/stack_blocks_three", 1.0, "robotwin50"),
        ("clean/stack_blocks_two", 1.0, "robotwin50"),
        ("clean/stack_bowls_three", 1.0, "robotwin50"),
        ("clean/stack_bowls_two", 1.0, "robotwin50"),
        ("clean/stamp_seal", 1.0, "robotwin50"),
        ("clean/turn_switch", 1.0, "robotwin50"),
        ("randomized/adjust_bottle", 1.0, "robotwin50"),
        ("randomized/beat_block_hammer", 1.0, "robotwin50"),
        ("randomized/blocks_ranking_rgb", 1.0, "robotwin50"),
        ("randomized/blocks_ranking_size", 1.0, "robotwin50"),
        ("randomized/click_alarmclock", 1.0, "robotwin50"),
        ("randomized/click_bell", 1.0, "robotwin50"),
        ("randomized/dump_bin_bigbin", 1.0, "robotwin50"),
        ("randomized/grab_roller", 1.0, "robotwin50"),
        ("randomized/handover_block", 1.0, "robotwin50"),
        ("randomized/handover_mic", 1.0, "robotwin50"),
        ("randomized/hanging_mug", 1.0, "robotwin50"),
        ("randomized/lift_pot", 1.0, "robotwin50"),
        ("randomized/move_can_pot", 1.0, "robotwin50"),
        ("randomized/move_pillbottle_pad", 1.0, "robotwin50"),
        ("randomized/move_playingcard_away", 1.0, "robotwin50"),
        ("randomized/move_stapler_pad", 1.0, "robotwin50"),
        ("randomized/open_laptop", 1.0, "robotwin50"),
        ("randomized/open_microwave", 1.0, "robotwin50"),
        ("randomized/pick_diverse_bottles", 1.0, "robotwin50"),
        ("randomized/pick_dual_bottles", 1.0, "robotwin50"),
        ("randomized/place_a2b_left", 1.0, "robotwin50"),
        ("randomized/place_a2b_right", 1.0, "robotwin50"),
        ("randomized/place_bread_basket", 1.0, "robotwin50"),
        ("randomized/place_bread_skillet", 1.0, "robotwin50"),
        ("randomized/place_burger_fries", 1.0, "robotwin50"),
        ("randomized/place_can_basket", 1.0, "robotwin50"),
        ("randomized/place_cans_plasticbox", 1.0, "robotwin50"),
        ("randomized/place_container_plate", 1.0, "robotwin50"),
        ("randomized/place_dual_shoes", 1.0, "robotwin50"),
        ("randomized/place_empty_cup", 1.0, "robotwin50"),
        ("randomized/place_fan", 1.0, "robotwin50"),
        ("randomized/place_mouse_pad", 1.0, "robotwin50"),
        ("randomized/place_object_basket", 1.0, "robotwin50"),
        ("randomized/place_object_scale", 1.0, "robotwin50"),
        ("randomized/place_object_stand", 1.0, "robotwin50"),
        ("randomized/place_phone_stand", 1.0, "robotwin50"),
        ("randomized/place_shoe", 1.0, "robotwin50"),
        ("randomized/press_stapler", 1.0, "robotwin50"),
        ("randomized/put_bottles_dustbin", 1.0, "robotwin50"),
        ("randomized/put_object_cabinet", 1.0, "robotwin50"),
        ("randomized/rotate_qrcode", 1.0, "robotwin50"),
        ("randomized/scan_object", 1.0, "robotwin50"),
        ("randomized/shake_bottle", 1.0, "robotwin50"),
        ("randomized/shake_bottle_horizontally", 1.0, "robotwin50"),
        ("randomized/stack_blocks_three", 1.0, "robotwin50"),
        ("randomized/stack_blocks_two", 1.0, "robotwin50"),
        ("randomized/stack_bowls_three", 1.0, "robotwin50"),
        ("randomized/stack_bowls_two", 1.0, "robotwin50"),
        ("randomized/stamp_seal", 1.0, "robotwin50"),
        ("randomized/turn_switch", 1.0, "robotwin50"),
    ],
    "robotwin_lerobot_mix_success":[
        ("clean/adjust_bottle", 1.0, "robotwin50"),
        ("clean/beat_block_hammer", 1.0, "robotwin50"),
        ("clean/blocks_ranking_rgb", 1.0, "robotwin50"),
        ("clean/blocks_ranking_size", 1.0, "robotwin50"),
        ("clean/click_alarmclock", 1.0, "robotwin50"),
        ("clean/click_bell", 1.0, "robotwin50"),
        ("clean/dump_bin_bigbin", 1.0, "robotwin50"),
        ("clean/grab_roller", 1.0, "robotwin50"),
        ("clean/handover_block", 1.0, "robotwin50"),
        ("clean/handover_mic", 1.0, "robotwin50"),
        ("clean/hanging_mug", 1.0, "robotwin50"),
        ("clean/lift_pot", 1.0, "robotwin50"),
        ("clean/move_can_pot", 1.0, "robotwin50"),
        ("clean/move_pillbottle_pad", 1.0, "robotwin50"),
        ("clean/move_playingcard_away", 1.0, "robotwin50"),
        ("clean/move_stapler_pad", 1.0, "robotwin50"),
        ("clean/open_laptop", 1.0, "robotwin50"),
        ("clean/open_microwave", 1.0, "robotwin50"),
        ("clean/pick_diverse_bottles", 1.0, "robotwin50"),
        ("clean/pick_dual_bottles", 1.0, "robotwin50"),
        ("clean/place_a2b_left", 1.0, "robotwin50"),
        ("clean/place_a2b_right", 1.0, "robotwin50"),
        ("clean/place_bread_basket", 1.0, "robotwin50"),
        ("clean/place_bread_skillet", 1.0, "robotwin50"),
        ("clean/place_burger_fries", 1.0, "robotwin50"),
        ("clean/place_can_basket", 1.0, "robotwin50"),
        ("clean/place_cans_plasticbox", 1.0, "robotwin50"),
        ("clean/place_container_plate", 1.0, "robotwin50"),
        ("clean/place_dual_shoes", 1.0, "robotwin50"),
        ("clean/place_empty_cup", 1.0, "robotwin50"),
        ("clean/place_fan", 1.0, "robotwin50"),
        ("clean/place_mouse_pad", 1.0, "robotwin50"),
        ("clean/place_object_basket", 1.0, "robotwin50"),
        ("clean/place_object_scale", 1.0, "robotwin50"),
        ("clean/place_object_stand", 1.0, "robotwin50"),
        ("clean/place_phone_stand", 1.0, "robotwin50"),
        ("clean/place_shoe", 1.0, "robotwin50"),
        ("clean/press_stapler", 1.0, "robotwin50"),
        ("clean/put_bottles_dustbin", 1.0, "robotwin50"),
        ("clean/put_object_cabinet", 1.0, "robotwin50"),
        ("clean/rotate_qrcode", 1.0, "robotwin50"),
        ("clean/scan_object", 1.0, "robotwin50"),
        ("clean/shake_bottle", 1.0, "robotwin50"),
        ("clean/shake_bottle_horizontally", 1.0, "robotwin50"),
        ("clean/stack_blocks_three", 1.0, "robotwin50"),
        ("clean/stack_blocks_two", 1.0, "robotwin50"),
        ("clean/stack_bowls_three", 1.0, "robotwin50"),
        ("clean/stack_bowls_two", 1.0, "robotwin50"),
        ("clean/stamp_seal", 1.0, "robotwin50"),
        ("clean/turn_switch", 1.0, "robotwin50"),
        ("randomized/adjust_bottle", 1.0, "robotwin50"),
        ("randomized/beat_block_hammer", 1.0, "robotwin50"),
        ("randomized/blocks_ranking_rgb", 1.0, "robotwin50"),
        ("randomized/blocks_ranking_size", 1.0, "robotwin50"),
        ("randomized/click_alarmclock", 1.0, "robotwin50"),
        ("randomized/click_bell", 1.0, "robotwin50"),
        ("randomized/dump_bin_bigbin", 1.0, "robotwin50"),
        ("randomized/grab_roller", 1.0, "robotwin50"),
        ("randomized/handover_block", 1.0, "robotwin50"),
        ("randomized/handover_mic", 1.0, "robotwin50"),
        ("randomized/hanging_mug", 1.0, "robotwin50"),
        ("randomized/lift_pot", 1.0, "robotwin50"),
        ("randomized/move_can_pot", 1.0, "robotwin50"),
        ("randomized/move_pillbottle_pad", 1.0, "robotwin50"),
        ("randomized/move_playingcard_away", 1.0, "robotwin50"),
        ("randomized/move_stapler_pad", 1.0, "robotwin50"),
        ("randomized/open_laptop", 1.0, "robotwin50"),
        ("randomized/open_microwave", 1.0, "robotwin50"),
        ("randomized/pick_diverse_bottles", 1.0, "robotwin50"),
        ("randomized/pick_dual_bottles", 1.0, "robotwin50"),
        ("randomized/place_a2b_left", 1.0, "robotwin50"),
        ("randomized/place_a2b_right", 1.0, "robotwin50"),
        ("randomized/place_bread_basket", 1.0, "robotwin50"),
        ("randomized/place_bread_skillet", 1.0, "robotwin50"),
        ("randomized/place_burger_fries", 1.0, "robotwin50"),
        ("randomized/place_can_basket", 1.0, "robotwin50"),
        ("randomized/place_cans_plasticbox", 1.0, "robotwin50"),
        ("randomized/place_container_plate", 1.0, "robotwin50"),
        ("randomized/place_dual_shoes", 1.0, "robotwin50"),
        ("randomized/place_empty_cup", 1.0, "robotwin50"),
        ("randomized/place_fan", 1.0, "robotwin50"),
        ("randomized/place_mouse_pad", 1.0, "robotwin50"),
        ("randomized/place_object_basket", 1.0, "robotwin50"),
        ("randomized/place_object_scale", 1.0, "robotwin50"),
        ("randomized/place_object_stand", 1.0, "robotwin50"),
        ("randomized/place_phone_stand", 1.0, "robotwin50"),
        ("randomized/place_shoe", 1.0, "robotwin50"),
        ("randomized/press_stapler", 1.0, "robotwin50"),
        ("randomized/put_bottles_dustbin", 1.0, "robotwin50"),
        ("randomized/put_object_cabinet", 1.0, "robotwin50"),
        ("randomized/rotate_qrcode", 1.0, "robotwin50"),
        ("randomized/scan_object", 1.0, "robotwin50"),
        ("randomized/shake_bottle", 1.0, "robotwin50"),
        ("randomized/shake_bottle_horizontally", 1.0, "robotwin50"),
        ("randomized/stack_blocks_three", 1.0, "robotwin50"),
        ("randomized/stack_blocks_two", 1.0, "robotwin50"),
        ("randomized/stack_bowls_three", 1.0, "robotwin50"),
        ("randomized/stack_bowls_two", 1.0, "robotwin50"),
        ("randomized/stamp_seal", 1.0, "robotwin50"),
        ("randomized/turn_switch", 1.0, "robotwin50"),
        ("aloha-agilex_v1_success/blocks_ranking_size", 1.0, "robotwin50"),
        ("aloha-agilex_v1_success/click_alarmclock", 1.0, "robotwin50"),
        ("aloha-agilex_v1_success/click_bell", 1.0, "robotwin50"),
        ("aloha-agilex_v1_success/hanging_mug", 1.0, "robotwin50"),
        ("aloha-agilex_v1_success/open_microwave", 1.0, "robotwin50"),
        ("aloha-agilex_v1_success/pick_diverse_bottles", 1.0, "robotwin50"),
        ("aloha-agilex_v1_success/place_bread_basket", 1.0, "robotwin50"),
        ("aloha-agilex_v1_success/place_bread_skillet", 1.0, "robotwin50"),
        ("aloha-agilex_v1_success/place_can_basket", 1.0, "robotwin50"),
        ("aloha-agilex_v1_success/put_bottles_dustbin", 1.0, "robotwin50"),
        ("aloha-agilex_v1_success/stack_blocks_three", 1.0, "robotwin50"),
        ("aloha-agilex_v1_success/turn_switch", 1.0, "robotwin50"),
        ("aloha-agilex_v2_success/blocks_ranking_size", 1.0, "robotwin50"),
        ("aloha-agilex_v2_success/click_alarmclock", 1.0, "robotwin50"),
        ("aloha-agilex_v2_success/click_bell", 1.0, "robotwin50"),
        ("aloha-agilex_v2_success/hanging_mug", 1.0, "robotwin50"),
        ("aloha-agilex_v2_success/open_microwave", 1.0, "robotwin50"),
        ("aloha-agilex_v2_success/pick_diverse_bottles", 1.0, "robotwin50"),
        ("aloha-agilex_v2_success/place_bread_basket", 1.0, "robotwin50"),
        ("aloha-agilex_v2_success/place_bread_skillet", 1.0, "robotwin50"),
        ("aloha-agilex_v2_success/place_can_basket", 1.0, "robotwin50"),
        ("aloha-agilex_v2_success/put_bottles_dustbin", 1.0, "robotwin50"),
        ("aloha-agilex_v2_success/stack_blocks_three", 1.0, "robotwin50"),
        ("aloha-agilex_v2_success/turn_switch", 1.0, "robotwin50"),
        ("aloha-agilex_v3_success/click_alarmclock", 1.0, "robotwin50"),
        ("aloha-agilex_v3_success/click_bell", 1.0, "robotwin50"),
        ("aloha-agilex_v3_success/hanging_mug", 1.0, "robotwin50"),
    ],
    "robotwin_lerobot_mix_success_failure":[
        ("clean/adjust_bottle", 1.0, "robotwin50"),
        ("clean/beat_block_hammer", 1.0, "robotwin50"),
        ("clean/blocks_ranking_rgb", 1.0, "robotwin50"),
        ("clean/blocks_ranking_size", 1.0, "robotwin50"),
        ("clean/click_alarmclock", 1.0, "robotwin50"),
        ("clean/click_bell", 1.0, "robotwin50"),
        ("clean/dump_bin_bigbin", 1.0, "robotwin50"),
        ("clean/grab_roller", 1.0, "robotwin50"),
        ("clean/handover_block", 1.0, "robotwin50"),
        ("clean/handover_mic", 1.0, "robotwin50"),
        ("clean/hanging_mug", 1.0, "robotwin50"),
        ("clean/lift_pot", 1.0, "robotwin50"),
        ("clean/move_can_pot", 1.0, "robotwin50"),
        ("clean/move_pillbottle_pad", 1.0, "robotwin50"),
        ("clean/move_playingcard_away", 1.0, "robotwin50"),
        ("clean/move_stapler_pad", 1.0, "robotwin50"),
        ("clean/open_laptop", 1.0, "robotwin50"),
        ("clean/open_microwave", 1.0, "robotwin50"),
        ("clean/pick_diverse_bottles", 1.0, "robotwin50"),
        ("clean/pick_dual_bottles", 1.0, "robotwin50"),
        ("clean/place_a2b_left", 1.0, "robotwin50"),
        ("clean/place_a2b_right", 1.0, "robotwin50"),
        ("clean/place_bread_basket", 1.0, "robotwin50"),
        ("clean/place_bread_skillet", 1.0, "robotwin50"),
        ("clean/place_burger_fries", 1.0, "robotwin50"),
        ("clean/place_can_basket", 1.0, "robotwin50"),
        ("clean/place_cans_plasticbox", 1.0, "robotwin50"),
        ("clean/place_container_plate", 1.0, "robotwin50"),
        ("clean/place_dual_shoes", 1.0, "robotwin50"),
        ("clean/place_empty_cup", 1.0, "robotwin50"),
        ("clean/place_fan", 1.0, "robotwin50"),
        ("clean/place_mouse_pad", 1.0, "robotwin50"),
        ("clean/place_object_basket", 1.0, "robotwin50"),
        ("clean/place_object_scale", 1.0, "robotwin50"),
        ("clean/place_object_stand", 1.0, "robotwin50"),
        ("clean/place_phone_stand", 1.0, "robotwin50"),
        ("clean/place_shoe", 1.0, "robotwin50"),
        ("clean/press_stapler", 1.0, "robotwin50"),
        ("clean/put_bottles_dustbin", 1.0, "robotwin50"),
        ("clean/put_object_cabinet", 1.0, "robotwin50"),
        ("clean/rotate_qrcode", 1.0, "robotwin50"),
        ("clean/scan_object", 1.0, "robotwin50"),
        ("clean/shake_bottle", 1.0, "robotwin50"),
        ("clean/shake_bottle_horizontally", 1.0, "robotwin50"),
        ("clean/stack_blocks_three", 1.0, "robotwin50"),
        ("clean/stack_blocks_two", 1.0, "robotwin50"),
        ("clean/stack_bowls_three", 1.0, "robotwin50"),
        ("clean/stack_bowls_two", 1.0, "robotwin50"),
        ("clean/stamp_seal", 1.0, "robotwin50"),
        ("clean/turn_switch", 1.0, "robotwin50"),
        ("randomized/adjust_bottle", 1.0, "robotwin50"),
        ("randomized/beat_block_hammer", 1.0, "robotwin50"),
        ("randomized/blocks_ranking_rgb", 1.0, "robotwin50"),
        ("randomized/blocks_ranking_size", 1.0, "robotwin50"),
        ("randomized/click_alarmclock", 1.0, "robotwin50"),
        ("randomized/click_bell", 1.0, "robotwin50"),
        ("randomized/dump_bin_bigbin", 1.0, "robotwin50"),
        ("randomized/grab_roller", 1.0, "robotwin50"),
        ("randomized/handover_block", 1.0, "robotwin50"),
        ("randomized/handover_mic", 1.0, "robotwin50"),
        ("randomized/hanging_mug", 1.0, "robotwin50"),
        ("randomized/lift_pot", 1.0, "robotwin50"),
        ("randomized/move_can_pot", 1.0, "robotwin50"),
        ("randomized/move_pillbottle_pad", 1.0, "robotwin50"),
        ("randomized/move_playingcard_away", 1.0, "robotwin50"),
        ("randomized/move_stapler_pad", 1.0, "robotwin50"),
        ("randomized/open_laptop", 1.0, "robotwin50"),
        ("randomized/open_microwave", 1.0, "robotwin50"),
        ("randomized/pick_diverse_bottles", 1.0, "robotwin50"),
        ("randomized/pick_dual_bottles", 1.0, "robotwin50"),
        ("randomized/place_a2b_left", 1.0, "robotwin50"),
        ("randomized/place_a2b_right", 1.0, "robotwin50"),
        ("randomized/place_bread_basket", 1.0, "robotwin50"),
        ("randomized/place_bread_skillet", 1.0, "robotwin50"),
        ("randomized/place_burger_fries", 1.0, "robotwin50"),
        ("randomized/place_can_basket", 1.0, "robotwin50"),
        ("randomized/place_cans_plasticbox", 1.0, "robotwin50"),
        ("randomized/place_container_plate", 1.0, "robotwin50"),
        ("randomized/place_dual_shoes", 1.0, "robotwin50"),
        ("randomized/place_empty_cup", 1.0, "robotwin50"),
        ("randomized/place_fan", 1.0, "robotwin50"),
        ("randomized/place_mouse_pad", 1.0, "robotwin50"),
        ("randomized/place_object_basket", 1.0, "robotwin50"),
        ("randomized/place_object_scale", 1.0, "robotwin50"),
        ("randomized/place_object_stand", 1.0, "robotwin50"),
        ("randomized/place_phone_stand", 1.0, "robotwin50"),
        ("randomized/place_shoe", 1.0, "robotwin50"),
        ("randomized/press_stapler", 1.0, "robotwin50"),
        ("randomized/put_bottles_dustbin", 1.0, "robotwin50"),
        ("randomized/put_object_cabinet", 1.0, "robotwin50"),
        ("randomized/rotate_qrcode", 1.0, "robotwin50"),
        ("randomized/scan_object", 1.0, "robotwin50"),
        ("randomized/shake_bottle", 1.0, "robotwin50"),
        ("randomized/shake_bottle_horizontally", 1.0, "robotwin50"),
        ("randomized/stack_blocks_three", 1.0, "robotwin50"),
        ("randomized/stack_blocks_two", 1.0, "robotwin50"),
        ("randomized/stack_bowls_three", 1.0, "robotwin50"),
        ("randomized/stack_bowls_two", 1.0, "robotwin50"),
        ("randomized/stamp_seal", 1.0, "robotwin50"),
        ("randomized/turn_switch", 1.0, "robotwin50"),
        ("aloha-agilex_v1_success/blocks_ranking_size", 1.0, "robotwin50"),
        ("aloha-agilex_v1_success/click_alarmclock", 1.0, "robotwin50"),
        ("aloha-agilex_v1_success/click_bell", 1.0, "robotwin50"),
        ("aloha-agilex_v1_success/hanging_mug", 1.0, "robotwin50"),
        ("aloha-agilex_v1_success/open_microwave", 1.0, "robotwin50"),
        ("aloha-agilex_v1_success/pick_diverse_bottles", 1.0, "robotwin50"),
        ("aloha-agilex_v1_success/place_bread_basket", 1.0, "robotwin50"),
        ("aloha-agilex_v1_success/place_bread_skillet", 1.0, "robotwin50"),
        ("aloha-agilex_v1_success/place_can_basket", 1.0, "robotwin50"),
        ("aloha-agilex_v1_success/put_bottles_dustbin", 1.0, "robotwin50"),
        ("aloha-agilex_v1_success/stack_blocks_three", 1.0, "robotwin50"),
        ("aloha-agilex_v1_success/turn_switch", 1.0, "robotwin50"),
        ("aloha-agilex_v2_success/blocks_ranking_size", 1.0, "robotwin50"),
        ("aloha-agilex_v2_success/click_alarmclock", 1.0, "robotwin50"),
        ("aloha-agilex_v2_success/click_bell", 1.0, "robotwin50"),
        ("aloha-agilex_v2_success/hanging_mug", 1.0, "robotwin50"),
        ("aloha-agilex_v2_success/open_microwave", 1.0, "robotwin50"),
        ("aloha-agilex_v2_success/pick_diverse_bottles", 1.0, "robotwin50"),
        ("aloha-agilex_v2_success/place_bread_basket", 1.0, "robotwin50"),
        ("aloha-agilex_v2_success/place_bread_skillet", 1.0, "robotwin50"),
        ("aloha-agilex_v2_success/place_can_basket", 1.0, "robotwin50"),
        ("aloha-agilex_v2_success/put_bottles_dustbin", 1.0, "robotwin50"),
        ("aloha-agilex_v2_success/stack_blocks_three", 1.0, "robotwin50"),
        ("aloha-agilex_v2_success/turn_switch", 1.0, "robotwin50"),
        ("aloha-agilex_v3_success/click_alarmclock", 1.0, "robotwin50"),
        ("aloha-agilex_v3_success/click_bell", 1.0, "robotwin50"),
        ("aloha-agilex_v3_success/hanging_mug", 1.0, "robotwin50"),
        ("aloha-agilex_v1_failure/blocks_ranking_size", 1.0, "robotwin50"),
        ("aloha-agilex_v1_failure/click_alarmclock", 1.0, "robotwin50"),
        ("aloha-agilex_v1_failure/click_bell", 1.0, "robotwin50"),
        ("aloha-agilex_v1_failure/hanging_mug", 1.0, "robotwin50"),
        ("aloha-agilex_v1_failure/open_microwave", 1.0, "robotwin50"),
        ("aloha-agilex_v1_failure/pick_diverse_bottles", 1.0, "robotwin50"),
        ("aloha-agilex_v1_failure/place_bread_basket", 1.0, "robotwin50"),
        ("aloha-agilex_v1_failure/place_bread_skillet", 1.0, "robotwin50"),
        ("aloha-agilex_v1_failure/place_can_basket", 1.0, "robotwin50"),
        ("aloha-agilex_v1_failure/put_bottles_dustbin", 1.0, "robotwin50"),
        ("aloha-agilex_v1_failure/stack_blocks_three", 1.0, "robotwin50"),
        ("aloha-agilex_v1_failure/turn_switch", 1.0, "robotwin50"),
        ("aloha-agilex_v2_failure/blocks_ranking_size", 1.0, "robotwin50"),
        ("aloha-agilex_v2_failure/click_alarmclock", 1.0, "robotwin50"),
        ("aloha-agilex_v2_failure/click_bell", 1.0, "robotwin50"),
        ("aloha-agilex_v2_failure/hanging_mug", 1.0, "robotwin50"),
        ("aloha-agilex_v2_failure/open_microwave", 1.0, "robotwin50"),
        ("aloha-agilex_v2_failure/pick_diverse_bottles", 1.0, "robotwin50"),
        ("aloha-agilex_v2_failure/place_bread_basket", 1.0, "robotwin50"),
        ("aloha-agilex_v2_failure/place_bread_skillet", 1.0, "robotwin50"),
        ("aloha-agilex_v2_failure/place_can_basket", 1.0, "robotwin50"),
        ("aloha-agilex_v2_failure/put_bottles_dustbin", 1.0, "robotwin50"),
        ("aloha-agilex_v2_failure/stack_blocks_three", 1.0, "robotwin50"),
        ("aloha-agilex_v2_failure/turn_switch", 1.0, "robotwin50"),
        ("aloha-agilex_v3_failure/blocks_ranking_size", 1.0, "robotwin50"),
        ("aloha-agilex_v3_failure/click_alarmclock", 1.0, "robotwin50"),
        ("aloha-agilex_v3_failure/click_bell", 1.0, "robotwin50"),
        ("aloha-agilex_v3_failure/hanging_mug", 1.0, "robotwin50"),
        ("aloha-agilex_v3_failure/open_microwave", 1.0, "robotwin50"),
        ("aloha-agilex_v3_failure/pick_diverse_bottles", 1.0, "robotwin50"),
        ("aloha-agilex_v3_failure/place_bread_basket", 1.0, "robotwin50"),
        ("aloha-agilex_v3_failure/place_bread_skillet", 1.0, "robotwin50"),
        ("aloha-agilex_v3_failure/place_can_basket", 1.0, "robotwin50"),
        ("aloha-agilex_v3_failure/put_bottles_dustbin", 1.0, "robotwin50"),
        ("aloha-agilex_v3_failure/stack_blocks_three", 1.0, "robotwin50"),
        ("aloha-agilex_v3_failure/turn_switch", 1.0, "robotwin50"),
        ("aloha-agilex_v4_success/blocks_ranking_size", 1.0, "robotwin50"),
        ("aloha-agilex_v4_success/click_alarmclock", 1.0, "robotwin50"),
        ("aloha-agilex_v4_success/click_bell", 1.0, "robotwin50"),
        ("aloha-agilex_v4_success/hanging_mug", 1.0, "robotwin50"),
        ("aloha-agilex_v4_success/open_microwave", 1.0, "robotwin50"),
        ("aloha-agilex_v4_success/pick_diverse_bottles", 1.0, "robotwin50"),
        ("aloha-agilex_v4_success/place_bread_basket", 1.0, "robotwin50"),
        ("aloha-agilex_v4_success/place_bread_skillet", 1.0, "robotwin50"),
        ("aloha-agilex_v4_success/place_can_basket", 1.0, "robotwin50"),
        ("aloha-agilex_v4_success/put_bottles_dustbin", 1.0, "robotwin50"),
        ("aloha-agilex_v4_success/stack_blocks_three", 1.0, "robotwin50"),
        ("aloha-agilex_v4_success/turn_switch", 1.0, "robotwin50"),
        ("aloha-agilex_v5_success/blocks_ranking_size", 1.0, "robotwin50"),
        ("aloha-agilex_v5_success/click_alarmclock", 1.0, "robotwin50"),
        ("aloha-agilex_v5_success/click_bell", 1.0, "robotwin50"),
        ("aloha-agilex_v5_success/hanging_mug", 1.0, "robotwin50"),
        ("aloha-agilex_v5_success/open_microwave", 1.0, "robotwin50"),
        ("aloha-agilex_v5_success/pick_diverse_bottles", 1.0, "robotwin50"),
        ("aloha-agilex_v5_success/place_bread_basket", 1.0, "robotwin50"),
        ("aloha-agilex_v5_success/place_bread_skillet", 1.0, "robotwin50"),
        ("aloha-agilex_v5_success/place_can_basket", 1.0, "robotwin50"),
        ("aloha-agilex_v5_success/put_bottles_dustbin", 1.0, "robotwin50"),
        ("aloha-agilex_v5_success/stack_blocks_three", 1.0, "robotwin50"),
        ("aloha-agilex_v5_success/turn_switch", 1.0, "robotwin50"),
        ("aloha-agilex_v6_success/blocks_ranking_size", 1.0, "robotwin50"),
        ("aloha-agilex_v6_success/click_alarmclock", 1.0, "robotwin50"),
        ("aloha-agilex_v6_success/click_bell", 1.0, "robotwin50"),
        ("aloha-agilex_v6_success/hanging_mug", 1.0, "robotwin50"),
        ("aloha-agilex_v6_success/open_microwave", 1.0, "robotwin50"),
        ("aloha-agilex_v6_success/pick_diverse_bottles", 1.0, "robotwin50"),
        ("aloha-agilex_v6_success/place_bread_basket", 1.0, "robotwin50"),
        ("aloha-agilex_v6_success/place_bread_skillet", 1.0, "robotwin50"),
        ("aloha-agilex_v6_success/place_can_basket", 1.0, "robotwin50"),
        ("aloha-agilex_v6_success/put_bottles_dustbin", 1.0, "robotwin50"),
        ("aloha-agilex_v6_success/stack_blocks_three", 1.0, "robotwin50"),
        ("aloha-agilex_v6_success/turn_switch", 1.0, "robotwin50"),
    ],
    "robotwin_lerobot_success":[
        ("aloha-agilex_v1_success/blocks_ranking_size", 1.0, "robotwin50"),
        ("aloha-agilex_v1_success/click_alarmclock", 1.0, "robotwin50"),
        ("aloha-agilex_v1_success/click_bell", 1.0, "robotwin50"),
        ("aloha-agilex_v1_success/hanging_mug", 1.0, "robotwin50"),
        ("aloha-agilex_v1_success/open_microwave", 1.0, "robotwin50"),
        ("aloha-agilex_v1_success/pick_diverse_bottles", 1.0, "robotwin50"),
        ("aloha-agilex_v1_success/place_bread_basket", 1.0, "robotwin50"),
        ("aloha-agilex_v1_success/place_bread_skillet", 1.0, "robotwin50"),
        ("aloha-agilex_v1_success/place_can_basket", 1.0, "robotwin50"),
        ("aloha-agilex_v1_success/put_bottles_dustbin", 1.0, "robotwin50"),
        ("aloha-agilex_v1_success/stack_blocks_three", 1.0, "robotwin50"),
        ("aloha-agilex_v1_success/turn_switch", 1.0, "robotwin50"),
        ("aloha-agilex_v2_success/blocks_ranking_size", 1.0, "robotwin50"),
        ("aloha-agilex_v2_success/click_alarmclock", 1.0, "robotwin50"),
        ("aloha-agilex_v2_success/click_bell", 1.0, "robotwin50"),
        ("aloha-agilex_v2_success/hanging_mug", 1.0, "robotwin50"),
        ("aloha-agilex_v2_success/open_microwave", 1.0, "robotwin50"),
        ("aloha-agilex_v2_success/pick_diverse_bottles", 1.0, "robotwin50"),
        ("aloha-agilex_v2_success/place_bread_basket", 1.0, "robotwin50"),
        ("aloha-agilex_v2_success/place_bread_skillet", 1.0, "robotwin50"),
        ("aloha-agilex_v2_success/place_can_basket", 1.0, "robotwin50"),
        ("aloha-agilex_v2_success/put_bottles_dustbin", 1.0, "robotwin50"),
        ("aloha-agilex_v2_success/stack_blocks_three", 1.0, "robotwin50"),
        ("aloha-agilex_v2_success/turn_switch", 1.0, "robotwin50"),
        ("aloha-agilex_v3_success/click_alarmclock", 1.0, "robotwin50"),
        ("aloha-agilex_v3_success/click_bell", 1.0, "robotwin50"),
        ("aloha-agilex_v3_success/hanging_mug", 1.0, "robotwin50"),
    ]
}
